### PR TITLE
CM-230: adds ocr recognition to create bovine

### PR DESCRIPTION
**Pull request by FranciscodeMaussion**

### CODE REVIEW

**Comment by AbrilViola** [comment]
test this please

**Comment by FranciscodeMaussion** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by FranciscodeMaussion** [comment]
test this please

**Comment by FranciscodeMaussion** [comment]
test this please

**Comment by AbrilViola** [comment]
test this please

**Pull request merged**
